### ISSUE TITLE
Turn off Full heal on capture Public server config

### ISSUE THREAD

**Issue by scaryguy334** [FortressOne/fortressonesv#20]
Lots of maps utilise capture goal ents in ways that conflict with this setting being turned on, eg Kotc + King (almost godmode standing on goal), Xpress3, trophy_b6 (removes conc effect on enemies on cap wut) etc..

Current solution would be to either have map specific settings, but easier would be just to turn this off in Public server config.

**Comment by drzel** [comment]
Done
